# Generated by Django 5.0.3 on 2024-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(blank=True, max_length=6, null=True)),
                ('confirmar_senha', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
